# Configuración SonarQube - Pharmacy Inventory System

sonar.projectKey=pharmacy-inventory-konex
sonar.projectName=Pharmacy Inventory System
sonar.projectVersion=1.0.0

sonar.sources=backend/pharmacy-inventory/src/main/java,frontend/pharmacy-inventory-ui/src/app
sonar.tests=backend/pharmacy-inventory/src/test/java,frontend/pharmacy-inventory-ui/src/app

# Java Backend
sonar.java.source=17
sonar.java.binaries=backend/pharmacy-inventory/target/classes
sonar.java.test.binaries=backend/pharmacy-inventory/target/test-classes
sonar.java.libraries=backend/pharmacy-inventory/target/*.jar

# Coverage Backend (JaCoCo)
sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=backend/pharmacy-inventory/target/site/jacoco/jacoco.xml

# TypeScript Frontend
sonar.typescript.lcov.reportPaths=frontend/pharmacy-inventory-ui/coverage/pharmacy-inventory-ui/lcov.info

# Exclusiones
sonar.exclusions=**/node_modules/**,**/target/**,**/*.spec.ts,**/*.spec.js,**/test/**,**/dist/**

# Encoding
sonar.sourceEncoding=UTF-8

# Language
sonar.language=java,ts
